create extension if not exists pgcrypto;

create table if not exists public.qr_campaigns (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  business_name text not null,
  destination_url text not null,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_scans (
  id bigint generated by default as identity primary key,
  campaign_id uuid references public.qr_campaigns(id) on delete cascade,
  slug text not null,
  ip_hash text,
  user_agent text,
  referrer text,
  created_at timestamptz not null default now()
);

alter table public.qr_campaigns enable row level security;
alter table public.qr_scans enable row level security;

-- This app uses the Supabase service role key only on secure server routes.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in browser code.

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_qr_campaigns_updated_at on public.qr_campaigns;
create trigger trg_qr_campaigns_updated_at
before update on public.qr_campaigns
for each row execute function public.touch_updated_at();

create or replace function public.get_qr_campaigns_with_counts()
returns table (
  id uuid,
  slug text,
  business_name text,
  destination_url text,
  notes text,
  active boolean,
  created_at timestamptz,
  updated_at timestamptz,
  scan_count bigint
)
language sql security definer as $$
  select c.id, c.slug, c.business_name, c.destination_url, c.notes, c.active, c.created_at, c.updated_at, count(s.id)::bigint as scan_count
  from public.qr_campaigns c
  left join public.qr_scans s on s.campaign_id = c.id
  group by c.id
  order by c.created_at desc;
$$;
