-- Clutch Connect: smart business card profiles, links, leads, and click analytics.
-- Additive migration to preserve existing QR and analytics behavior.

alter table public.qr_codes
  add column if not exists qr_type text not null default 'url',
  add column if not exists profile_id uuid;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  business_name text,
  contact_name text,
  title text,
  phone text,
  email text,
  website text,
  bio text,
  avatar_url text,
  cover_url text,
  theme_color text not null default '#FFA665',
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint profiles_customer_id_unique unique (customer_id)
);

create table if not exists public.profile_links (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  label text not null,
  url text not null,
  icon text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.profile_leads (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  name text,
  email text,
  phone text,
  message text,
  honeypot text,
  ip_hash text,
  user_agent text,
  created_at timestamptz default now()
);

create table if not exists public.profile_click_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  profile_link_id uuid references public.profile_links(id) on delete set null,
  event_type text not null check (event_type in (
    'profile_view',
    'call_click',
    'text_click',
    'email_click',
    'website_click',
    'vcard_download',
    'link_click',
    'lead_submit'
  )),
  metadata jsonb,
  ip_hash text,
  user_agent text,
  created_at timestamptz default now()
);

alter table public.qr_codes
  drop constraint if exists qr_codes_qr_type_check;

alter table public.qr_codes
  add constraint qr_codes_qr_type_check
  check (qr_type in ('url', 'connect_profile'));

alter table public.qr_codes
  add constraint qr_codes_profile_id_fkey
  foreign key (profile_id) references public.profiles(id) on delete set null;

create index if not exists profiles_customer_id_idx on public.profiles(customer_id);
create index if not exists profiles_slug_idx on public.profiles(slug);
create index if not exists profile_links_profile_id_idx on public.profile_links(profile_id);
create index if not exists profile_links_sort_order_idx on public.profile_links(profile_id, sort_order);
create index if not exists profile_leads_profile_id_idx on public.profile_leads(profile_id);
create index if not exists profile_leads_created_at_idx on public.profile_leads(created_at);
create index if not exists profile_click_events_profile_id_idx on public.profile_click_events(profile_id);
create index if not exists profile_click_events_event_type_idx on public.profile_click_events(event_type);
create index if not exists profile_click_events_created_at_idx on public.profile_click_events(created_at);
create index if not exists qr_codes_qr_type_idx on public.qr_codes(qr_type);
create index if not exists qr_codes_profile_id_idx on public.qr_codes(profile_id);

create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.profile_links enable row level security;
alter table public.profile_leads enable row level security;
alter table public.profile_click_events enable row level security;

-- Profiles: owners/admins can manage; public can read only active profiles.
drop policy if exists "Public can view active profiles" on public.profiles;
create policy "Public can view active profiles"
  on public.profiles
  for select
  using (is_active = true or public.current_user_is_admin() or customer_id in (
    select id from public.customers where auth_user_id = auth.uid()
  ));

drop policy if exists "Owners and admins can manage profiles" on public.profiles;
create policy "Owners and admins can manage profiles"
  on public.profiles
  for all
  using (
    public.current_user_is_admin() or customer_id in (
      select id from public.customers where auth_user_id = auth.uid()
    )
  )
  with check (
    public.current_user_is_admin() or customer_id in (
      select id from public.customers where auth_user_id = auth.uid()
    )
  );

-- Links: public can read active links on active profiles; owners/admins manage all.
drop policy if exists "Public can view active profile links" on public.profile_links;
create policy "Public can view active profile links"
  on public.profile_links
  for select
  using (
    (is_active = true and profile_id in (
      select p.id from public.profiles p where p.is_active = true
    ))
    or public.current_user_is_admin()
    or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  );

drop policy if exists "Owners and admins can manage profile links" on public.profile_links;
create policy "Owners and admins can manage profile links"
  on public.profile_links
  for all
  using (
    public.current_user_is_admin() or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  )
  with check (
    public.current_user_is_admin() or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  );

-- Leads and click events: owners/admins read; public insert only for active profiles.
drop policy if exists "Owners and admins can view profile leads" on public.profile_leads;
create policy "Owners and admins can view profile leads"
  on public.profile_leads
  for select
  using (
    public.current_user_is_admin() or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  );

drop policy if exists "Public can submit profile leads" on public.profile_leads;
create policy "Public can submit profile leads"
  on public.profile_leads
  for insert
  with check (profile_id in (
    select id from public.profiles where is_active = true
  ));

drop policy if exists "Owners and admins can view profile click events" on public.profile_click_events;
create policy "Owners and admins can view profile click events"
  on public.profile_click_events
  for select
  using (
    public.current_user_is_admin() or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  );

drop policy if exists "Public can submit profile click events" on public.profile_click_events;
create policy "Public can submit profile click events"
  on public.profile_click_events
  for insert
  with check (profile_id in (
    select id from public.profiles where is_active = true
  ));

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.profile_links to authenticated;
grant select on public.profile_leads to authenticated;
grant select on public.profile_click_events to authenticated;
grant insert on public.profile_leads to anon, authenticated;
grant insert on public.profile_click_events to anon, authenticated;
