-- Track Apple Wallet and Google Wallet adds for Clutch Connect profiles.

create table if not exists public.wallet_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  wallet_type text not null check (wallet_type in ('apple', 'google')),
  ip_hash text,
  user_agent text,
  created_at timestamptz default now()
);

create index if not exists wallet_events_profile_id_idx on public.wallet_events(profile_id);
create index if not exists wallet_events_wallet_type_idx on public.wallet_events(wallet_type);
create index if not exists wallet_events_created_at_idx on public.wallet_events(created_at);

alter table public.wallet_events enable row level security;

drop policy if exists "Owners and admins can view wallet events" on public.wallet_events;
create policy "Owners and admins can view wallet events"
  on public.wallet_events
  for select
  using (
    public.current_user_is_admin() or profile_id in (
      select p.id from public.profiles p
      join public.customers c on c.id = p.customer_id
      where c.auth_user_id = auth.uid()
    )
  );

drop policy if exists "Public can submit wallet events" on public.wallet_events;
create policy "Public can submit wallet events"
  on public.wallet_events
  for insert
  with check (profile_id in (
    select id from public.profiles where is_active = true
  ));

grant select on public.wallet_events to authenticated;
grant insert on public.wallet_events to anon, authenticated;
